modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/KnightMiner/Inspirations/issues/"
license="MIT"
[[mods]]
modId="inspirations"
version="${version}"
displayName="Inspirations"
displayURL="https://github.com/KnightMiner/Inspirations/wiki"
# logoFile="examplemod.png" #optional
credits="/u/nox-cgt for the idea and texture for heartbeets"
authors="KnightMiner"
description='''
Adds many small features with a vareity of inspirations.
'''
[[dependencies.inspirations]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.inspirations]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.inspirations]]
    modId="mantle"
    mandatory=true
    versionRange="${mantle_range}"
    ordering="AFTER"
    side="BOTH"
